name: onepay_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  json_annotation: ^2.0.0
  recase: ^3.0.0
  country_code_picker: ^1.4.0
  material_design_icons_flutter: ^4.0.5555
  ff_navigation_bar: ^0.1.5
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.10
#  barcode_scan: ^3.0.1
  qr_flutter: ^3.2.0
  fluttertoast: ^7.0.4
  share: ^0.6.5
  flutter_money_formatter: ^0.8.3
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: ComicSans
      fonts:
        - asset: assets/fonts/comic sans/ComicSansMS3.ttf
        - asset: assets/fonts/comic sans/design.graffiti.comicsansmsgras.ttf
          weight: 700

    - family: Segoe UI
      fonts:
        - asset: assets/fonts/segoe ui/Segoe UI.ttf
        - asset: assets/fonts/segoe ui/Segoe UI Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700

    - family: CustomIcons
      fonts:
        - asset: assets/icons/custom-icons.ttf

