/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData number_1 = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_1_filled = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_2 = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_3 = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_money_filled = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_money = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_filled = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onepay_logo = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onepay_logo_filled = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_simple = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_secured = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_ringing = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_mail = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_sms = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_mail_secured = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData complete = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData survey = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_triangle = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
